---
services:
  movies:
    image: aiyappaaa/movies
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: aiyappaaa/train
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: aiyappaaa/dth
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: aiyappaaa/recharge
    ports:
      - 84:80
    deploy:
      replicas: 3
