services:
  movies:
    image: aiyappaaa/movies
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: aiyappaaa/paytrain
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: aiyappaa/paydth
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: aiyappaaa/payrecharge
    ports:
      - 84:80
    deploy:
      replicas: 3
